import type { Record_ } from "./entry";

// Verb usage block (規劃書 06 §4.1, §7.3, screen L6). Stored on the entry
// itself as `VocabEntry.usage`, generated once and regenerated by hand.

export interface UsagePattern {
  // e.g. "sugarcoat + 名詞"
  pattern: string;
  meaningZh: string;
  example: string;
}

export interface UsageRelated {
  // e.g. "gloss over"
  phrase: string;
  zh: string;
}

export interface UsageBlock {
  patterns: UsagePattern[];
  related: UsageRelated[];
  // When the verb first got a usage block (加入日期); kept across
  // 重新產生. Absent on blocks from before it existed: generatedAt stands in.
  createdAt?: string;
  // The latest (re)generation (更新日期).
  generatedAt: string;
  model: string;
}

// partOfSpeech is free text from the dictionary ("verb", "Verb, noun",
// "transitive verb", "v.", "動詞"). "adverb" must not count.
const VERB_RE = /(?<![a-z])verb\b|(?<![a-z])v\.(?![a-z])|動詞/i;

export function isVerb(partOfSpeech: string | undefined): boolean {
  return !!partOfSpeech && VERB_RE.test(partOfSpeech);
}

// A verb's usage saved (收藏) to its word page — the L6 「寫入單字頁」
// button (1005 回饋 #4). Persisted in store/learn.json beside the saved
// trivia (LearnStore). One per verb: the id is derived from the entry, so
// two devices that save the same verb end up with one record, and an
// unsave is a tombstone that merges like any other edit (learnMerge.ts).
// The usage itself stays on the entry (VocabEntry.usage); the word page's
// 用法 section shows whatever is there now.
export interface VerbFavorite extends Record_ {
  id: string;
  entryId: string;
  // The verb as it was spelled when saved, for when the entry is gone.
  word: string;
}

export function verbFavoriteId(entryId: string): string {
  return `verb:${entryId}`;
}
