// Verb usage block (規劃書 06 §4.1, §7.3, screen L6). Stored on the entry
// itself as `VocabEntry.usage`, generated once and regenerated by hand.

export interface UsagePattern {
  // e.g. "sugarcoat + 名詞"
  pattern: string;
  meaningZh: string;
  example: string;
}

export interface UsageRelated {
  // e.g. "gloss over"
  phrase: string;
  zh: string;
}

export interface UsageBlock {
  patterns: UsagePattern[];
  related: UsageRelated[];
  generatedAt: string;
  model: string;
}

// partOfSpeech is free text from the dictionary ("verb", "Verb, noun",
// "transitive verb", "v.", "動詞"). "adverb" must not count.
const VERB_RE = /(?<![a-z])verb\b|(?<![a-z])v\.(?![a-z])|動詞/i;

export function isVerb(partOfSpeech: string | undefined): boolean {
  return !!partOfSpeech && VERB_RE.test(partOfSpeech);
}
