import { getLocale, t, type I18nKey } from "../../core/i18n";
import type { ExportLabels } from "./types";

// Headings and fixed text written into exported notes, in the plugin's
// current language (`export.*` keys in core/i18n).

// Labels added for the 1005 feedback, not in core/i18n yet (integration
// moves them to `export.usageSaved` / `export.usageGenerated`).
const L: Record<"zh-TW" | "en", Record<"usageSaved" | "usageGenerated", string>> = {
  "zh-TW": { usageSaved: "已收藏 {date}", usageGenerated: "AI 產生於 {date}" },
  en: { usageSaved: "Saved {date}", usageGenerated: "Generated by AI {date}" },
};

const KEYS: (keyof ExportLabels)[] = [
  "families",
  "familiesEmpty",
  "usage",
  "usageEmpty",
  "usageRelated",
  "trivia",
  "triviaEmpty",
  "triviaMentionedIn",
  "discussion",
  "discussionEmpty",
  "userNotesHint",
  "paragraphsEmpty",
  "paragraphOrphaned",
  "wordsLearned",
  "wordsEmpty",
  "wordQuestions",
  "favorites",
  "favoritesEmpty",
  "aborted",
  "usageSaved",
  "usageGenerated",
];

export function exportLabels(): ExportLabels {
  const labels = {} as ExportLabels;
  const extra = L[getLocale()] ?? L.en;
  for (const key of KEYS) {
    if (key in extra) labels[key] = t(`export.${key}` as I18nKey) ?? extra[key as keyof typeof extra];
    else labels[key] = t(`export.${key}` as I18nKey);
  }
  return labels;
}
