import { getLocale } from "../../core/i18n";

// Temporary strings for the M7 learning blocks (vocab-families, vocab-verbs,
// vocab-trivia) until they move into core/i18n/{zh-TW,en}.ts (規劃書 07 §2
// rule 3). Keys are already the dictionary keys they'll get there, so the
// move is: copy each pair into the two dictionaries, then replace `lt(` with
// `t(` in the three blocks.
//
// [zh-TW, en]
export const LEARN_STRINGS = {
  "learn.loading": ["載入中…", "Loading…"],
  "learn.stop": ["停止", "Stop"],
  "learn.retry": ["重試", "Retry"],
  "learn.ai.offline": ["目前離線，連線後才能使用 AI。已存的內容照常顯示。", "You're offline. Saved content still shows; AI needs a connection."],
  "learn.ai.disabled.title": ["AI 目前關閉", "AI is turned off"],
  "learn.ai.noKey.title": ["設定 AI 後才能使用", "Set up AI to use this"],
  "learn.ai.body": ["到「設定 › Vocab Tracker」設定 AI。已存的內容照常顯示。", "Set up AI in Settings › Vocab Tracker. Saved content still shows."],
  "learn.notFound": ["單字庫裡沒有「{word}」。", "\"{word}\" isn't in your vocab list."],

  "learn.family.empty.title": ["還沒有字族", "No word families yet"],
  "learn.family.empty.body": [
    "讓 AI 從你學過的單字整理出字族，再挑想學的新字加入單字庫。",
    "Let AI group the words you've learned into families, then pick new words to add.",
  ],
  "learn.family.word.empty.title": ["「{word}」還沒有字族", "\"{word}\" isn't in a family yet"],
  "learn.family.generate": ["找字族", "Find families"],
  "learn.family.regroup": ["重新分群", "Regroup"],
  "learn.family.regroup.hint": [
    "單字庫比上次分群時多了 20% 以上，要重新分群嗎？",
    "Your list has grown by 20% or more since the last grouping. Regroup?",
  ],
  "learn.family.regroup.note": ["存下後會取代目前由 AI 整理的字族。", "Saving replaces the families AI grouped before."],
  "learn.family.generating": ["AI 正在整理字族…", "Grouping your words…"],
  "learn.family.found": ["AI 找到 {families} 個字族、{words} 個新字", "Found {families} families and {words} new words"],
  "learn.family.noneFound": ["AI 沒有找到可以成為字族的字，換個時間再試試。", "No families this time. Try again later."],
  "learn.family.from": ["從你學過的 {words} 延伸", "grown from {words}"],
  "learn.family.known": ["已學", "Learned"],
  "learn.family.discard": ["捨棄", "Discard"],
  "learn.family.saveOnly": ["只存字族", "Save families only"],
  "learn.family.saveAdd": ["存字族，並把 {n} 個字加入單字庫", "Save, and add {n} words"],
  "learn.family.addNote": [
    "加入的字會自動查字典補資料，來源標記為「字族：{topics}」。",
    "Added words are looked up in the dictionary and marked as from \"family: {topics}\".",
  ],
  "learn.family.saved": ["已存 {families} 個字族，加入 {words} 個字。", "Saved {families} families and added {words} words."],
  "learn.family.added": ["已加入「{word}」", "Added \"{word}\""],
  "learn.family.add": ["加入「{word}」", "Add \"{word}\""],
  "learn.family.legend.known": ["已在單字庫", "In your list"],
  "learn.family.legend.suggested": ["AI 補的延伸字，點一下加入", "Suggested by AI — tap to add"],
  "learn.family.legend.seeds": ["起點：你學過的 {words}", "Started from {words}"],
  "learn.family.more": ["更多", "More"],
  "learn.family.delete": ["刪除這個字族", "Delete this family"],
  "learn.family.deleted": ["已刪除字族「{name}」", "Deleted family \"{name}\""],

  "learn.verb.filter": ["篩選動詞…", "Filter verbs…"],
  "learn.verb.count": ["已學動詞（{n}）", "Learned verbs ({n})"],
  "learn.verb.none.title": ["單字庫裡還沒有動詞", "No verbs in your list yet"],
  "learn.verb.none.body": ["詞性含 verb 的單字會出現在這裡。", "Words whose part of speech includes \"verb\" show up here."],
  "learn.verb.noMatch": ["沒有符合的動詞", "No matching verbs"],
  "learn.verb.notVerb": ["「{word}」不是動詞，沒有用法可以產生。", "\"{word}\" isn't a verb, so there's no usage to generate."],
  "learn.verb.generate": ["產生用法", "Generate usage"],
  "learn.verb.regenerate": ["重新產生", "Regenerate"],
  "learn.verb.generating": ["AI 正在整理 {word} 的用法…", "Working out how {word} is used…"],
  "learn.verb.empty.title": ["還沒有 {word} 的用法", "No usage for {word} yet"],
  "learn.verb.empty.body": [
    "讓 AI 整理常見句型、例句和相近說法。產生一次就會存起來。",
    "Let AI list common patterns, examples and similar expressions. It's saved once generated.",
  ],
  "learn.verb.related": ["相近說法", "Similar expressions"],
  "learn.verb.meta.source": ["出自 {source}", "From {source}"],
  "learn.verb.meta.generated": ["{date} 由 AI 產生", "Generated by AI on {date}"],
  "learn.verb.speak": ["發音", "Pronounce"],
  "learn.verb.hasUsage": ["已產生用法", "Usage generated"],

  "learn.trivia.title": ["單字冷知識", "Word trivia"],
  "learn.trivia.random": ["從已學的 {n} 個字隨機", "Random from your {n} words"],
  "learn.trivia.subject": ["主角：{word}", "About: {word}"],
  "learn.trivia.pick": ["指定一個字來聊", "Pick a word to talk about"],
  "learn.trivia.pick.placeholder": ["想聊哪個字？", "Which word?"],
  "learn.trivia.placeholder": ["追問這則冷知識…", "Ask a follow-up…"],
  "learn.trivia.footer": [
    "每則 50–200 字；同一個字講過的內容會記下來，不會重複。",
    "50–200 characters each. What's been told is remembered, so it won't repeat.",
  ],
  "learn.trivia.empty.title": ["單字庫還是空的", "Your vocab list is empty"],
  "learn.trivia.empty.body": ["加入幾個單字後，就能聽它們的冷知識。", "Add a few words, then come back for trivia about them."],
  "learn.trivia.noWords": ["沒有可以聊的單字。", "No words to talk about."],
  "learn.trivia.turn.next": ["冷知識", "Trivia"],
  "learn.trivia.favorites": ["收藏的冷知識", "Saved trivia"],
  "learn.trivia.favorites.empty": [
    "還沒有收藏。在回答下面點「收藏」，就會出現在這裡。",
    "Nothing saved yet. Tap \"Save\" under an answer to keep it here.",
  ],
  "learn.trivia.favorite": ["收藏", "Save"],
  "learn.trivia.favoriteTo": ["收藏到 {word}", "Save to {word}"],
  "learn.trivia.favorited": ["已收藏", "Saved"],
  "learn.trivia.unfavorite": ["取消收藏", "Remove"],
  "learn.trivia.up": ["有幫助", "Helpful"],
  "learn.trivia.down": ["沒幫助", "Not helpful"],
  "learn.trivia.mentions": ["也提到 {words}", "Also mentions {words}"],
} as const satisfies Record<string, readonly [string, string]>;

export type LearnKey = keyof typeof LEARN_STRINGS;

export function lt(key: LearnKey, params?: Record<string, string | number>): string {
  const [zh, en] = LEARN_STRINGS[key];
  const template: string = getLocale() === "zh-TW" ? zh : en;
  if (!params) return template;
  return template.replace(/\{(\w+)\}/g, (match, name: string) => (name in params ? String(params[name]) : match));
}

// 「aprons、kitchenware」 / "aprons, kitchenware".
export function joinWords(words: readonly string[]): string {
  return words.join(getLocale() === "zh-TW" ? "、" : ", ");
}
